version: 2
jobs:
  test:
    docker:
      - image: node:chakracore-10.13.0
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install modules
          command: npm install
      - save_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test

workflows:
  version: 2
  test:
    jobs:
      - test