version: 2
jobs:
  crowdin-upload:
    docker:
      - image: dougley/crowdin
    steps:
      - checkout
      - run: crowdin upload sources
  test:
    docker:
      - image: node:chakracore-10.13.0
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install modules
          command: npm install
      - save_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
  deploy:
    docker:
      - image: node:chakracore-10.13.0
    steps:
      - checkout
      - run:
          name: Install modules
          command: npm install
      - run:
          name: Create wrangler.toml
          command: echo -e "name = \"$CLOUDFLARE_WORKER_NAME\"\ntype = \"webpack\"\nzone_id = \"$CLOUDFLARE_ZONE_ID\"\nprivate = false\naccount_id = \"$CLOUDFLARE_ACCOUNT_ID\"\nroute = \"$CLOUDFLARE_ROUTE\"" > wrangler.toml
      - run:
          name: Install Wrangler Globally
          command: npm install wrangler -g
      - run:
          name: Configure Wrangler
          command: wrangler config $CLOUDFLARE_EMAIL $CLOUDFLARE_API_KEY
      - run:
          name: Deploy
          command: npm

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: /master|dev/
  deploy:
    jobs:
      - test:
          filters:
            branches:
              only: /master|dev/
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: /master|dev/