name: Docker Hub

on:
  push:
    branches:
      - master

jobs:
  description:
    name: Description
    runs-on: ubuntu-latest
    steps:
        - name: Docker Hub Description
          uses: peter-evans/dockerhub-description@v2.1.0
          env:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            DOCKERHUB_REPOSITORY: switchbladebot/invidget
